apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: e04njx0ey-go 
  janus-idp.io/tekton: e04njx0ey-go
  backstage.io/kubernetes-id: e04njx0ey-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e04njx0ey-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  